# Generated by Django 5.0 on 2026-08-03 22:26

import django.db.models.functions.text
from django.db import migrations, models


def remove_old_test_accounts(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
        migrations.RunPython(remove_old_test_accounts, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='users_username_case_insensitive_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='users_email_case_insensitive_unique'),
        ),
    ]
