# Generated by Django 5.0 on 2026-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationattempt_delete_phoneverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Даёт доступ к разделу модерации объявлений.'),
        ),
    ]
