# Generated by Django 5.2.17 on 2026-08-11 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('listing_approved', 'Объявление одобрено'), ('listing_rejected', 'Объявление отклонено'), ('listing_blocked', 'Объявление заблокировано'), ('listing_unblocked', 'Объявление разблокировано'), ('account_blocked', 'Аккаунт заблокирован'), ('account_unblocked', 'Аккаунт разблокирован')], max_length=24),
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.TextField()),
                ('was_active', models.BooleanField(default=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unblocked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unblock_note', models.TextField(blank=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_blocks', to=settings.AUTH_USER_MODEL)),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_user_blocks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'блокировка аккаунта',
                'verbose_name_plural': 'блокировки аккаунтов',
                'ordering': ('-blocked_at', '-pk'),
                'indexes': [models.Index(fields=['unblocked_at', 'expires_at'], name='user_block_expiry_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unblocked_at__isnull', True)), fields=('user',), name='user_one_active_block')],
            },
        ),
    ]
