# Generated by Django 5.2.17 on 2026-08-12 20:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def discard_legacy_registration_attempts(apps, schema_editor):
    RegistrationAttempt = apps.get_model('users', 'RegistrationAttempt')
    RegistrationAttempt.objects.all().delete()


def verify_existing_email_addresses(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(email='').update(email=None)
    User.objects.exclude(email__isnull=True).exclude(email='').update(
        is_email_verified=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notification_kind_userblock'),
    ]

    operations = [
        migrations.RunPython(
            discard_legacy_registration_attempts,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='registrationattempt',
            name='phone',
        ),
        migrations.AddField(
            model_name='registrationattempt',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            verify_existing_email_addresses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='registrationattempt',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationattempt',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EmailCodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('password_reset', 'Восстановление пароля'), ('email_change', 'Смена email')], db_index=True, max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_code_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['purpose', 'email', '-created_at'], name='email_code_purpose_idx')],
            },
        ),
    ]
