# Generated by Django 5.2.17 on 2026-08-17

from django.db import migrations, models


def discard_unconfirmed_registration_attempts(apps, schema_editor):
    RegistrationAttempt = apps.get_model("users", "RegistrationAttempt")
    RegistrationAttempt.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_registrationattempt_phone_and_more"),
    ]

    operations = [
        migrations.RunPython(
            discard_unconfirmed_registration_attempts,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="registrationattempt",
            name="privacy_consent_at",
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name="registrationattempt",
            name="privacy_policy_version",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="registrationattempt",
            name="terms_accepted_at",
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name="registrationattempt",
            name="terms_version",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_policy_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_version",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
