# Generated by Django 5.2.17 on 2026-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_moderationdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На модерации"),
                    ("published", "Опубликовано"),
                    ("rejected", "Отклонено"),
                    ("archived", "Снято с публикации"),
                    ("completed", "Сделка завершена"),
                    ("deleted", "Удалено"),
                ],
                db_index=True,
                default="draft",
                max_length=12,
            ),
        ),
    ]
