# Generated by Django 5.2.17 on 2026-08-11 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_deleted_at_alter_listing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('fraud', 'Мошенничество'), ('duplicate', 'Дубликат'), ('incorrect', 'Неверная информация'), ('unavailable', 'Объект уже недоступен'), ('offensive', 'Недопустимое содержание'), ('other', 'Другое')], max_length=16)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('confirmed', 'Подтверждена'), ('dismissed', 'Отклонена')], db_index=True, default='pending', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listing_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'жалоба на объявление',
                'verbose_name_plural': 'жалобы на объявления',
                'ordering': ('created_at', 'pk'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='report_status_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('listing', 'reporter'), name='listing_report_one_pending')],
            },
        ),
    ]
