# Generated by Django 5.2.17 on 2026-08-11 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'Снято с публикации'), ('completed', 'Сделка завершена'), ('blocked', 'Заблокировано модератором'), ('deleted', 'Удалено')], db_index=True, default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='ListingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.TextField()),
                ('previous_status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'Снято с публикации'), ('completed', 'Сделка завершена'), ('blocked', 'Заблокировано модератором'), ('deleted', 'Удалено')], max_length=12)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unblocked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unblock_note', models.TextField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_blocks', to='listings.listing')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listing_blocks', to=settings.AUTH_USER_MODEL)),
                ('unblocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_listing_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'блокировка объявления',
                'verbose_name_plural': 'блокировки объявлений',
                'ordering': ('-blocked_at', '-pk'),
                'indexes': [models.Index(fields=['unblocked_at', 'expires_at'], name='listing_block_expiry_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unblocked_at__isnull', True)), fields=('listing',), name='listing_one_active_block')],
            },
        ),
    ]
