# Generated by Django 5.2.17 on 2026-08-12 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_status_listingblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Необязательно. Этот номер будет виден на странице объявления.', max_length=16, validators=[django.core.validators.RegexValidator(message='Введите номер в международном формате, например +992900001122.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Номер для связи'),
        ),
    ]
