# Generated by Django 5.0 on 2026-08-08

import uuid

from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    Message = apps.get_model("chat", "Message")
    for model in (Conversation, Message):
        for item in model.objects.filter(public_id__isnull=True).iterator():
            item.public_id = uuid.uuid4()
            item.save(update_fields=("public_id",))


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Канонический ключ пары участников и объявления.",
                max_length=96,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_message_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="client_id",
            field=models.UUIDField(
                blank=True,
                help_text="Идентификатор клиента для защиты от повторной отправки.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="conversation",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="message_conversation_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("conversation", "client_id"),
                name="message_conv_client_unique",
            ),
        ),
    ]
